# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: az400m05l05a-pool
  demands:
    - agent.name -equals az400m05-vm0
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    echo Starting install...
    npm install
  displayName: 'npm install'
  
- script: |
    echo Starting building...
    npm run build
  displayName: 'npm build'

- script: |
    echo Starting testing...
    npm test
    echo Finish pipeline...
  displayName: 'npm test'



